# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python Build/Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        # flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with our own tools
      run: |
        sh ./download-models.sh
        cd converter
        python firenet-conversion.py
        python inceptionVxOnFire-conversion.py -m 1
        python inceptionVxOnFire-conversion.py -m 3
        python inceptionVxOnFire-conversion.py -m 4
        python firenet-validation.py
        python inceptionVxOnFire-validation.py -m 1
        python inceptionVxOnFire-validation.py -m 3
        python inceptionVxOnFire-validation.py -m 4
        python inceptionVxOnFire-validation.py -m 1 -sp
        python inceptionVxOnFire-validation.py -m 3 -sp
        python inceptionVxOnFire-validation.py -m 4 -sp
